function [BW_out,properties] = C2_M4_filterRegions(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 07-Jan-2025
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[20000, 25393]);

% Get properties.
properties = regionprops(BW_out, {'Area', 'ConvexArea', 'FilledArea', 'MajorAxisLength', 'MinorAxisLength', 'Orientation'});